[package]
name = "manas"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A Redis-compatible in-memory database focusing on string operations"

[dependencies]
# We'll add dependencies as we need them
